### ISSUE TITLE
[영양제] 데이터 업데이트

### ISSUE THREAD

**Issue by TheSongOfSongs** [dnd-side-project/dnd-5th-2-backend#10]
- 영양제 정보 표시에 '평균 별점', '별점 개수' 추가 부탁드립니다.
- 해당 url은 다음과 같습니다. {{url}}/supplements/:supplementId

**Comment by sangmin7648** [comment]
다음 필드들을 추가 했습니다. 
- supplementAvgRating 
- supplementRatingCount

**Comment by sangmin7648** [comment]
이슈 올린 사람도 닫을 수 있나요? 닫을 수 있으면 확인하고 닫아주시고 못닫으면 댓글 남겨주세요

**Comment by TheSongOfSongs** [comment]
> 이슈 올린 사람도 닫을 수 있나요? 닫을 수 있으면 확인하고 닫아주시고 못닫으면 댓글 남겨주세요

닫았습니다~!
