### ISSUE TITLE
로그인 이메일 예외처리

### ISSUE THREAD

**Issue by sangmin7648** [dnd-side-project/dnd-5th-2-backend#18]
로그인에서 이메일 존재 여부를 확인하지 않아 서버 에러가 발생합니다

**Comment by sangmin7648** [comment]
테스트 해보고 이슈 닫을게요

**Comment by sangmin7648** [comment]
status code 200을 반환하는데 이부분 수정필요합니다. 그리고 저는 메시지를 객체로 보지않아 json으로 보내지 않고 단순 문자열로 보내는데 이부분 통일 필요할거 같아요

**Comment by jadeneu** [comment]
네 저는 보통 메시지 리턴할 때 이렇게 처리해왔어서 json으로 보냈었는데, 어떻게 해도 상관없긴 합니다. 어떤 방식을 더 선호하시나요
