### ISSUE TITLE
JSON key값 수정 요청

### ISSUE THREAD

**Issue by TheSongOfSongs** [dnd-side-project/dnd-5th-2-backend#53]
현재 서버에서 사용자의 유형 정보를 보낼 때 json key 값이 아래와 같습니다.
하나로 통일 부탁드립니다~!
  
- 사용자 유형 설정 : type
- 사용자 본인 정보 표시, 로그인 : type_name

**Comment by jadeneu** [comment]
넵 확인했습니다!
